import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ticketsPath, homePath } from "@/paths";
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          className="
            flex justify-between 
            supports-backdrop-blur:bg-background/60
            fixed left-0 right-0 top-0 z-20 bg-background/95 backdrop-blur
            w-full p-5 border-b"
        >
          <Button asChild variant={"outline"}>
            <Link href={homePath()}>Home</Link>
            {/* as child property lets just the anchor tag appear in the DOM */}
          </Button>
          <Link
            href={ticketsPath()}
            className={buttonVariants({ variant: "outline" })}
          >
            Tickets
          </Link>
          {/* same outcome, different approach */}
        </nav>
        <main
          className="
             min-h-screen flex-1 
             overflow-x-hidden overflow-y-auto 
             bg-secondary/20 flex flex-col 
             py-24 px-8 
        "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
